### ISSUE TITLE
打开已有文件无法预览

### ISSUE THREAD

**Issue by ahjsrhj** [wordmark/wordmark#1]
打开已有文件无法预览，只有全选，剪切粘贴之后才有预览出现。
版本是2.1.0 os x版

**Comment by ahjsrhj** [comment]
还有一个问题。。选择发布到github报错
![](http://i.imgur.com/aBo7uvO.png)

**Comment by wordmark** [comment]
感谢报错。会尽快修复！

**Comment by wordmark** [comment]
Thank you for the issue. Will fix it asap.

**Comment by wordmark** [comment]
Fixed Chinese post publishing to Github bug.
