### ISSUE TITLE
如果我想把WordMark 作为笔记本

### ISSUE THREAD

**Issue by unh1de** [wordmark/wordmark#10]
你好，是否考虑这种用途，而加强侧边栏，比如
1. 侧边栏分类
2. 本地文档集中放着一位置，有一目录，而不是我每次去选择存在哪里，选择位置。

另外提个建议：导出为图片，发邮件的时候非常有用。。

**Comment by wordmark** [comment]
感谢您的建议。考虑中...

**Comment by wordmark** [comment]
Added
