### ISSUE TITLE
Download link for Linux versions fails

### ISSUE THREAD

**Issue by Torsten-K** [wordmark/wordmark#108]
On your website, the download link for the latest Linux version (Ubuntu .deb file) only leads to an error page – here on GitHub, there does not seem to be a compiled version for Linux any longer. Why is that?

**Comment by wordmark** [comment]
Hi there, sorry for late reply. I haven't got time to set up a linux machine and environment at this moment. Will do it soon.

**Comment by Torsten-K** [comment]
Ah, I see, thanks for informing.
