### ISSUE TITLE
WordPress添加失败

### ISSUE THREAD

**Issue by SubtleMuffin** [wordmark/wordmark#11]
自己搭建的WordPress，总是提示Cannot fetch the data, please check your network settings. （我确定它可以访问到我的WordPress，通过proxifier）不知道是WordPress的设置问题还是这个功能出现了问题。

**Comment by wordmark** [comment]
@zhengnanlee 抱歉给你带来不便。请问能否把您的 Wordpress 地址发送到 hi@wordmarkapp.com 以便调查？谢谢。

**Comment by wordmark** [comment]
@zhengnanlee 经调查，bug为博客为https所致。将在下一版本修复，谢谢。

**Comment by wordmark** [comment]
Fixed in 2.1.6
