### ISSUE TITLE
Wordmark 3.1.0 .deb file has unmet dependencies

### ISSUE THREAD

**Issue by johnblommers** [wordmark/wordmark#111]
The installer file `wordmark_3.1.0_x64.deb` will not install because the GNOME Eddy installer reports:

```bash
The following packages have unmet dependencies:
  wordmark: Depends: libgtk-3-0 but it is not installable
            Depends: libnotify4 but it is not installable
            Depends: libnss3 but it is not installable
            Depends: libxtst6 but it is not installable
            Depends: libatspi2.0-0 but it is not installable
            Depends: libdrm2 but it is not installable
            Depends: libgbm1 but it is not installable
            Depends: libxcb-dri3-0 but it is not installable
```

So I thought to use Gdebi instead and it reports an incorrect CPU architecture:

```bash
sudo gdebi wordmark_3.1.0_x64.deb 

Reading package lists... Done
Building dependency tree        
Reading state information... Done
This package is uninstallable
Wrong architecture 'x64' -- Run dpkg --add-architecture to add it and update afterwards
```

Undeterred I tried next:

```bash
sudo dpkg -i wordmark_3.1.0_x64.deb 
dpkg: error processing archive wordmark_3.1.0_x64.deb (--install):
 package architecture (x64) does not match system (amd64)
Errors were encountered while processing:
 wordmark_3.1.0_x64.deb
```

These errors prevent installing Wordmark. It seems the `.deb` file isn't properly configured? The package `libgtk-3-3` is in fact installed on the system. So it seems the CPU version setting is wrong in the `.deb` file.

**Update.**

**And it is**. The Control file in the `.deb` bundle  indicates `x86` when in fact it should indicate `amd64`. By following the instructions [Unpack, modify and repack deb files](http://tuxdiary.com/2013/12/01/unpack-modify-and-repack-deb-files/) I was able to reconstruct the `.deb` file and successfully install this update.

This is on my up-to-date 64-bit Pop-os system version 20.10 based on Ubuntu 20.10 and running GNOME 3.38.3 with kernel 5.11.0.

**Comment by wordmark** [comment]
Thank you for all the details. Probabaly it was because I built the package using M1 chip macbook. I will see if I can just find a linux machine and build a new one.

**Comment by wordmark** [comment]
Updated deb with 3.1.1, let me know if the issue persists. Thanks.
