### ISSUE TITLE
wrong arch error at installation

### ISSUE THREAD

**Issue by ggrrll** [wordmark/wordmark#112]
![Screenshot from 2021-05-26 17-36-59](https://user-images.githubusercontent.com/15370425/119689389-19392e80-be49-11eb-9b03-5ce1fa4f9407.png)

on linux Mint 20.1 
(Intel© Core™ i7)

**Comment by johnblommers** [comment]
See [Issue 111 Wordmark 3.1.0 .deb file has unmet dependencies](https://github.com/wordmark/wordmark/issues/111). You can unpack the `.deb`, edit `x64` to `arm64` in the control file, and repack the `.deb` file yourself. That worked for me.
