### ISSUE TITLE
Can't open markdown files with word mark from within finder

### ISSUE THREAD

**Issue by CamilleScholtz** [wordmark/wordmark#114]
Nor can I make word mark the default app to open markdown files. I can only open these files by opening word mark and opening the file from within the popup there. This is for the wordmark app found on the Mac App Store.

**Comment by wordmark** [comment]
Thank you for the report. At this moment WordMark Mac app doesn't support open a file directly but it will be added soon.

**Comment by wordmark** [comment]
Will support this feature in Version 56 (macOS).
