### ISSUE TITLE
Add support for toml front matter

### ISSUE THREAD

**Issue by CamilleScholtz** [wordmark/wordmark#115]
Mostly designated using `+++` instead of `---` (yaml)

**Comment by wordmark** [comment]
May I ask what the motivation for this support? Is there a static blog framework using toml? Thanks.

**Comment by CamilleScholtz** [comment]
Yes, hugo has the option of yaml , toml and json front matter: https://gohugo.io/content-management/front-matter/

**Comment by wordmark** [comment]
Will be supported in v56 (macOS)
