### ISSUE TITLE
提一些建议

### ISSUE THREAD

**Issue by bestswifter** [wordmark/wordmark#14]
1. 更新新版本后，原来添加的图床和博客似乎不见了，建议确认一下是否是bug
2. 如果能增加 Vim 模式，那就太棒了！
3. 期待添加 [TOC] 功能，效果参考马克飞象。

**Comment by wordmark** [comment]
@bestswifter 感谢您的建议和意见，现答复如下：
1. 更新过程中由于数据存储的改变可能会造成设置改变，非常抱歉！下次更新会尽量改变这种情况。
2. 考虑添加中...
3. 考虑添加中...
