### ISSUE TITLE
您好，2.1.6 Windows 64位版本有点小问题

### ISSUE THREAD

**Issue by kylingit** [wordmark/wordmark#15]
2.1.6 Windows 64位版本，添加Github publish后，directory path该怎么填写？设置为根目录或者blog目录post下，都会报“The post already exists. Please change the name”
还有，设置语言后重启，过一会儿又会恢复成原来的样子...设置不起作用

**Comment by wordmark** [comment]
@kylingit 您好，2.1.6暂不支持添加根目录，如果添加blog目录，根据Github的API规则，请移除开始的斜杠"/"。例如，如果blog目录为"posts"，请直接填写"posts"而不是"/posts“。将在下一版本自动移除斜杠并允许添加根目录。

**Comment by wordmark** [comment]
@kylingit 关于语言自动切换的问题..能否请您详细描述一下？是再次重启后恢复，还是使用过程中突然切换回原来的语言？谢谢！

**Comment by kylingit** [comment]
@wordmark 设置语言后重启后生效，但是再进行某些设置时(比如设置github push)再次恢复成原来的语言，即在使用过程中突然切换回去了。对使用不产生影响。这个问题在linux下也是如此(4.2.0-35-generic -Ubuntu)。软件挺好用的，这些小问题再改善一下会选择付费支持，感谢~
PS. 第一个问题解决了，是自己设置的问题，path填source/_posts即可。

**Comment by wordmark** [comment]
Fixed in 2.1.7
