### ISSUE TITLE
发布到印象笔记出错

### ISSUE THREAD

**Issue by xzonepiece** [wordmark/wordmark#19]
发布到印象笔记后，并未在印象笔记中找到，打开浏览器，出现“undefined”

**Comment by wordmark** [comment]
@xzonepiece 您好，感谢反馈。经测试暂无法重现错误。请问您使用的WordMark版本、操作系统、印象笔记还是Evernote？谢谢！

**Comment by xzonepiece** [comment]
@wordmark WordMark2.1.12+windows7+印象笔记 我又试了一下，可惜还是不行，打开浏览器，出现**“undefined" 不是一个有效的 Note Guid**，没有其他内容

**Comment by xu-wy** [comment]
遇到同样问题。版本 2.1.13 windows10.印象笔记。第一次可以正常发布，之后就无法发布，在印象笔记中也无法找到。

**Comment by wordmark** [comment]
@xu-wy @xzonepiece 感谢回复。经调查发现Evernote在提交前会验证所有`<a/>`和`<img/>`标签中的URL是否为合法路径。请问发布的文档中是否可能含有无效的URL路径？（例如`[链接](somerandomlink.info/vip.html)`为无效）

有效的URL类似 `http://www.xxx.com/yyy.png` 或者 `https://ttt.xxx/ddd`

谢谢！

**Comment by xu-wy** [comment]
今天更新2.2.0之后，发现问题解决了，之前测试发现，只要带有markdown语法的链接都是无法同步到印象笔记的。
