### ISSUE TITLE
上传图片到ghost 无法显示 

### ISSUE THREAD

**Issue by Ohuisang** [wordmark/wordmark#2]

**Comment by wordmark** [comment]
Thanks for the issue. Working on it.

**Comment by wordmark** [comment]
@LinBling 测试了一下，图片正常。能否麻烦提供一下错误详情（WordMark版本、操作系统、使用的Ghost版本等），谢谢！

![screen shot 2016-05-19 at 3 29 15 pm](https://cloud.githubusercontent.com/assets/18313215/15411674/73e9bbec-1dd6-11e6-8275-50b376d7b134.png)

**Comment by Ohuisang** [comment]
试了下，发现有些图片可以有些不行。不清楚什么原因，可能是图片问题。(WordMark 2.1.3, Ghost 0.7.9, OS 10.11.5) 谢谢回复。话说能实现 Ghost  发过的文章能修改更新？目前只能发草稿和发布，文章发布后，WordMark里的文章就没什么用了。

![7f19bb48-81c0-420f-8562-1d022f5a2782](https://cloud.githubusercontent.com/assets/4980617/15415143/5619eb76-1e73-11e6-9a03-d8d7c59db9bb.png)

**Comment by wordmark** [comment]
@LinBling 你好，已经定位bug，将在下一版本修复，谢谢！

**Comment by wordmark** [comment]
Fixed in 2.1.4
