### ISSUE TITLE
貌似新版本2.1.13还没打包吧

### ISSUE THREAD

**Issue by MrLeo** [wordmark/wordmark#20]
貌似新版本2.1.13还没打包吧。下载的release地址只到2.1.9

**Comment by wordmark** [comment]
抱歉，可能昨天没看好上传完毕就发布了。我稍后会重新发布一下2.1.13.

**Comment by wordmark** [comment]
2.1.13重新发布 https://github.com/wordmark/wordmark/releases/tag/v2.1.13
