### ISSUE TITLE
能否增加国内下载

### ISSUE THREAD

**Issue by chineselzh** [wordmark/wordmark#24]
能否增加国内下载地址？国外的下载太慢，几KB的速度没法下载。。。
下载几分钟就显示下载失败！
可以使用国内的`七牛`作为下载源，或者百度网盘也行，谢谢！
国外下载速度如下图：
![](http://i4.piimg.com/567571/7017dee1e8199de1.png)

**Comment by wordmark** [comment]
@chineselzh 感谢建议。已增加[百度网盘链接](https://pan.baidu.com/s/1hrMUka4)

**Comment by chineselzh** [comment]
收到，谢谢！
