### ISSUE TITLE
鼠标光标位置偏移

### ISSUE THREAD

**Issue by jaybenjaminlee** [wordmark/wordmark#27]
打字时间长了之后会出现，光标位置与实际位置不一致的问题

**Comment by wordmark** [comment]
能否提供一下使用的WordMark版本？谢谢！

**Comment by jaybenjaminlee** [comment]
v2.2.0 @wordmark

**Comment by wordmark** [comment]
Fixed in [v2.2.1](https://github.com/wordmark/wordmark/releases/tag/v2.2.1).
