### ISSUE TITLE
你好，改了字体后，打开空白~~

### ISSUE THREAD

**Issue by unh1de** [wordmark/wordmark#3]
[如图所示](https://dl.dropboxusercontent.com/s/xfp1y2yc1v3y4ad/2016-05-19%20at%2023.28.png)

**Comment by wordmark** [comment]
Thanks for the issue. Working on it.

**Comment by wordmark** [comment]
@unh1de 经过测试暂时无法重现错误，能否麻烦提供更详细信息？
1. WordMark版本
2. 更换字体名字？
3. 重启软件后是否正常？
谢谢！

**Comment by unh1de** [comment]
@wordmark 你好，是 v0.36.12，本来设置 Source Code Pro 字体，但看见中文不太好看，设置了一个就PingFang，可能字体名称错了，没起作用，删掉后，没输入字体名称。去看别的了，等会设置页面就打不开了，关闭软件后就空白了，重启动软件重启动电脑都打不开。

**Comment by unh1de** [comment]
有办法重置没有，现在用不了呢。

原始邮件
发件人:WordMarknotifications@github.com
收件人:wordmark/wordmarkwordmark@noreply.github.com
抄送:Jorbhi@jorb.me; Mentionmention@noreply.github.com
发送时间:2016年5月20日(周五) 07:18
主题:Re: [wordmark/wordmark] 你好，改了字体后，打开空白~~ (#3)

@unh1de 经过测试暂时无法重现错误，能否麻烦提供更详细信息？
1. WordMark版本
2. 更换字体名字？
3. 重启软件后是否正常？
   谢谢！

**Comment by wordmark** [comment]
@unh1de 你好，可否留一个联系邮箱，或者发送邮件到 hi@wordmarkapp.com 谢谢！

**Comment by wordmark** [comment]
2.1.4 更换字体修改方式，希望能解决问题。
