### ISSUE TITLE
这个APP是不是WEB APP？

### ISSUE THREAD

**Issue by leion8310** [wordmark/wordmark#31]
这是Web App吧，发现加载大文件的时候会很卡

**Comment by NoahDragon** [comment]
是用electron为内核的应用。Electron代表作是Atom，加载大文件也很卡。

**Comment by leion8310** [comment]
VS Code 好像也是用 Electron，打开一样的文件却很流畅，但Atom也很慢，不知道是不是优化的原因~

**Comment by leion8310** [comment]
刚又试了下，文件用Atom打开也很快，但WorkMark就很卡，不知道怎么回事，WorkMark能设置运行的内存大小吗？

**Comment by wordmark** [comment]
@leion8310 感谢提问。WordMark是基于Electron的应用。测试过10万行的`md`文件，打开延迟500ms左右，使用并无明显卡顿，但有提升空间。
