### ISSUE TITLE
添加文件夹之后，关闭 APP，再次打开 APP 之后，文件夹点击展开不管用

### ISSUE THREAD

**Issue by jaybenjaminlee** [wordmark/wordmark#35]

**Comment by wordmark** [comment]
可能是由于升级后导致的新旧版本用户文件不一致造成。请问是否试过[重设WordMark](http://wordmarkapp.com/faq/#how-to-reset-wordmark)？谢谢！

**Comment by jaybenjaminlee** [comment]
macOS:
Purchased from the Mac App Store: open Finder and press Command+shift+G, enter ~/Library/Containers/im.liuhao.wordmark/Data/Library/Application Support, find and remove “WordMark” folder

按照上面的操作，仍然未解决

**Comment by wordmark** [comment]
经调查是Mac App Store的sandbox（沙盒）限制，导致软件重启后用户选择的文件夹失去打开权限。这个问题也造成了您在 https://github.com/wordmark/wordmark/issues/37 提到的路径丢失问题。解决中... 同时，您也可以试用WordMark的[非MAS版](http://wordmarkapp.com/)，由于您已经购买MAS版本，您可以发送邮件至 hi@wordmarkapp.com 获得免费的授权码。注：非MAS版由于无沙盒限制并没有路径bug。

**Comment by jaybenjaminlee** [comment]
邮件已发，发件人 jay******ee@icloud.com
