### ISSUE TITLE
重启软件，文件路径丢失

### ISSUE THREAD

**Issue by jaybenjaminlee** [wordmark/wordmark#37]
![image](https://cloud.githubusercontent.com/assets/3771580/17657885/72362836-62f9-11e6-9104-32a7820317e8.png)

![image](https://cloud.githubusercontent.com/assets/3771580/17657871/567030a6-62f9-11e6-8fc7-11be94cbec1d.png)

当编辑一个文件时，关闭 APP 之后再打开，文件路径丢失

**Comment by wordmark** [comment]
Same reason as https://github.com/wordmark/wordmark/issues/35
