### ISSUE TITLE
你好，提几点意见~

### ISSUE THREAD

**Issue by unh1de** [wordmark/wordmark#4]
Wordmark的功能非常完善，是一个非常不错的Markdown写作+发布软件！我需要的功能都齐全了，写作+发布+图片自动上图床。软件界面也漂亮，而且很便宜，良心软件。

如果能加强一下几点，那是件更完美的事情。
1. Markdown代码高亮,很多Markdown编辑器已经做到。
2. 中文显示效果更佳
3. Ghost 文章载入本地？然后可以随时修改发布，现在使用需要回到后台操作。也不知道Ghost 允许做到这些事情不。
4. 多几套主题，你的另一个作品 [子阅](http://ziyue.io/) 的主题就不错。
5. 多几套Markdown显示方案

**Comment by wordmark** [comment]
非常感谢您的建议！

**Comment by Ohuisang** [comment]
第三點 表示如果能做到完全可以放棄 ghost 后台的编辑了。

**Comment by wordmark** [comment]
好像已经都实现了 @unh1de 提到的几点。如果有新的建议或者更多问题请重开这个issue或者开一个新的，谢谢！
