### ISSUE TITLE
请问可以回水吗！！！！拜托版本稳定了再收费吧

### ISSUE THREAD

**Issue by MRMIKKO** [wordmark/wordmark#41]
# 请问可以回水吗！！！！30蚊买个测试版返嚟！！！！
- 切换语言后，左侧工作区挂了，要删除再打开再能用
- **常用快捷键可以多设几个吗 ？图片的，链接的，加粗的，斜体的**~~~
- 居然没有导出 html 文件
- 说好的 PDF 导出呢？
- **刚打开文档 Command + Z，文档内容全没了。。。。。**

**Comment by wordmark** [comment]
你好，
1. 工作区无法正常工作为Mac App Store版的已知bug，由于MAS版沙盒限制，需要用户重新打开文件夹WordMark才有权限访问，解决方式请使用非MAS版。
2. 相对路径：请确保勾选设置中“相对路径”选项，另外请确认Markdown文件需已经保存在本地后才能使用相对路径
3. 4. 打开预览后点击右下角图标即可导出HTML或PDF。
   <img width="157" alt="screen shot 2016-08-23 at 7 25 58 pm" src="https://cloud.githubusercontent.com/assets/18313215/17916349/6d57f622-6967-11e6-9aac-1c94762524d1.png">

谢谢。

**Comment by MRMIKKO** [comment]
- 常用快捷键可以多设几个吗 ？图片的，链接的，加粗的，斜体的~~~
- 刚打开文档 Command + Z，文档内容全没了

**Comment by wordmark** [comment]
感谢回复。关于第一个问题，目前WordMark支持加粗和斜体，您可以在编辑界面右键点击查看，图片和链接暂不支持，但在支持计划中。第二个问题，undo导致的内容丢失将在下一版本修复。谢谢！

**Comment by wordmark** [comment]
Fixed in [2.2.4](https://github.com/wordmark/wordmark/releases/tag/v2.2.4)
