### ISSUE TITLE
升级到2.2.4后，正在编辑的文章也没了。。。

### ISSUE THREAD

**Issue by Ohuisang** [wordmark/wordmark#42]
App Store 没上架 2.2.4 之前，在官网下过2.2.4 一样的情况，还以为测试版有问题。用回2.2.2文档编辑的就显示出来了，路径问题吧。如图工作区文章也不见了：

![154f0205-d6ef-45fa-8632-0a78ff0eb11f](https://cloud.githubusercontent.com/assets/4980617/18038032/3f7b4f7c-6dc4-11e6-89a5-6f3ccbbfbcaf.png)

**Comment by wordmark** [comment]
请问是否与这个问题描述一致？ http://wordmarkapp.com/faq/#why-all-my-opened-files-and-folders-are-lost-after-reboot
