### ISSUE TITLE
添加flickr服务发生错误

### ISSUE THREAD

**Issue by xzonepiece** [wordmark/wordmark#45]
![无法添加flickr图床接口](http://7oxfwx.com1.z0.glb.clouddn.com/2016_09_01_2016-09-01_110006.png_litterpicture)
wordmark版本号2.2.4
windows7 x64

**Comment by wordmark** [comment]
经测试，有时会有这个问题，怀疑原因为Flickr API不稳定。如果重试几次是否能解决呢？谢谢！

**Comment by xzonepiece** [comment]
@wordmark 至少我试了5、6次都没成功，有时候直接就是空白，连error错误框都没有
