### ISSUE TITLE
增加VIM编辑模式的建议

### ISSUE THREAD

**Issue by leion8310** [wordmark/wordmark#46]
增加VIM编辑模式的建议

**Comment by wordmark** [comment]
你好，Vim模式可以在设置中打开。

**Comment by wordmark** [comment]
<img width="449" alt="screen_shot_2016-09-01_at_11_34_53_pm" src="https://cloud.githubusercontent.com/assets/18313215/18194748/c45f27d8-709c-11e6-8408-7278d9b66c69.png">

**Comment by leion8310** [comment]
看到了，谢谢！
