### ISSUE TITLE
如何获取序列号

### ISSUE THREAD

**Issue by kissinggod** [wordmark/wordmark#5]
想请问一下在官网通过FastSpring付款后，如何才能获取序列号？谢谢！

**Comment by fuermosi777** [comment]
@kissinggod 您好，您应该在付款后收到一封含有序列号的邮件。如果您没有收到的话，请查看一下垃圾邮件夹，或者请把您购买时填写的邮箱发送到 hi@wordmarkapp.com 谢谢！

**Comment by kissinggod** [comment]
@fuermosi777 感谢您的回复，我查看了一下垃圾邮箱，没有收到相关邮件。现在就将相关信息发去。

**Comment by kissinggod** [comment]
@fuermosi777 邮件已发，烦请查核一下。非常感谢！

**Comment by wordmark** [comment]
@kissinggod 已将序列号发送至邮箱，如未收到，请麻烦告知，谢谢！
