### ISSUE TITLE
引用格式显示问题（如图）

### ISSUE THREAD

**Issue by jaybenjaminlee** [wordmark/wordmark#55]
![image](https://cloud.githubusercontent.com/assets/3771580/18571602/36bb1360-7be6-11e6-8586-493af761b963.png)

**Comment by wordmark** [comment]
感谢问题。@jaybenjaminlee WordMark 在引用中遵循 Markdown 的作者的语法：https://daringfireball.net/projects/markdown/syntax#blockquote 如下图所示。

<img width="757" alt="screen shot 2016-09-20 at 2 43 26 pm" src="https://cloud.githubusercontent.com/assets/18313215/18689955/9b3660bc-7f40-11e6-84a5-d14546402264.png">
