### ISSUE TITLE
HTTPS  的 Ghost 博客无法添加

### ISSUE THREAD

**Issue by miantiao-me** [wordmark/wordmark#6]

**Comment by aaronbu** [comment]
碰到了同样的问题 似乎用http添加成功

**Comment by wordmark** [comment]
@ccbikai @aaronbu 感谢...将在下一版本修复此问题，添加https/http选项

**Comment by miantiao-me** [comment]
@wordmark https 正常添加，上传的图片返回地址有问题。

Ghost 0.8.0, 使用了七牛存储插件。https://github.com/minwe/qn-store

应该判断返回的图片是否以 http 开头，来确定是否使用域名 

错误代码：

```
![Untitled Image](https://chi.miantiao.mehttps://dn-mtimg.qbox.me/ghost/2016/05/codemark-1464405452788.jpg)
```

**Comment by wordmark** [comment]
Fixed
