### ISSUE TITLE
发布到  Ghost 的3个建议

### ISSUE THREAD

**Issue by miantiao-me** [wordmark/wordmark#7]
1. 能否自动提取文字开头的 `# abc`  中的 abc 自动作为标题；
2. ghost 支持标签；
3. 发布为草稿，根据软件提示点击，浏览器打开是 404， 建议使用 https://chi.miantiao.me/p/41a6a081-085c-4c96-ac9a-f0f9e3d97a1b/  这种网址预览 。

**Comment by wordmark** [comment]
Complete 1, 3. 

Won't do 2 until Ghost starts to support Tag in API. Thanks!
