### ISSUE TITLE
WordPress发布地址不支持https？

### ISSUE THREAD

**Issue by hu3rror** [wordmark/wordmark#70]
如果添加http的博客地址，可以成功添加服务，但是无法发布，并显示`failed to fetch`。
如果直接添加https的博客地址，直接显示`failed to fetch`。
我的WordPress是设置了强制https跳转的，不知道是不是这个原因导致wordmark的发布失效。
谢谢！

**Comment by huzhanfei** [comment]
我之前https的也可以添加，可是最近突然连接不上了！同样failed to fetch

**Comment by wordmark** [comment]
WordMark 3.x should have fixed this. Please reopen if it still exist.
