### ISSUE TITLE
[BUG]当使用七牛华南存储区域的时候，就会报错incorrect zone, please use up-z1.qiniu.com

### ISSUE THREAD

**Issue by blue7wings** [wordmark/wordmark#76]
![qq20170425-1](https://cloud.githubusercontent.com/assets/4016570/25371562/f8c95788-29c3-11e7-8577-251fd5af84e4.png)
华南，华北的上传URL，不一样导致的问题，希望也可以修改一下
![image](https://cloud.githubusercontent.com/assets/4016570/25371630/3f8decec-29c4-11e7-8d9d-0de9afab9ae8.png)

**Comment by neohoy** [comment]
incorrect region, please use up-z2.qiniu.com
