### ISSUE TITLE
3.0版本貌似不支持七牛。

### ISSUE THREAD

**Issue by fyxsky** [wordmark/wordmark#81]
Hi
3.0版本好像不支持七牛图床。
所以我安装了2.2.5版本。
但是付款的时候，被告知支付不成功。
所以，有两个问题：
* 3.0是否会支持七牛。
* 支付不成功是偶然现象，还是关闭了支付通道？（我是否应该再次尝试支付）

**Comment by wordmark** [comment]
Hi there,

1. Will WordMark 3.0 support Qiniu?
- Yes. All publishing and image services in 2.0 will be brought back soon.
2. Does WordMark 2.0 close payment channel?
- No. It looks like a Fastspring issue (the payment platform WordMark 2.0 is using). Could you please send your inquiry to hi@wordmarkapp.com? Thanks and sorry for the inconveniences.

**Comment by fyxsky** [comment]
OK ,Thanks.
I will be waiting for WordMark 3.0, and try to pay again.

**Comment by wordmark** [comment]
Should be fixed in beta-19. Feel free to reopen this.
