### ISSUE TITLE
The folder opened by history is not recorded under win, and the folder does not support hierarchical display, only the last level directory can be opened.

### ISSUE THREAD

**Issue by handbye** [wordmark/wordmark#82]
win下不记录历史打开的文件夹，另外文件夹也不支持层级显示，只能打开最后一级目录。

The folder opened by history is not recorded under win, and the folder does not support hierarchical display, only the last level directory can be opened.

**Comment by wordmark** [comment]
Hi @handbye , thanks for reaching out. What version are you using? Thanks :)

**Comment by handbye** [comment]
@wordmark  version is 3.0.1-deta.3    thanks

**Comment by fuermosi777** [comment]
Hi @handbye , thanks for reply. Are you able to see the following icon after opening a folder?
![untitled](https://user-images.githubusercontent.com/7303373/41084717-c5e45482-69e9-11e8-970a-877c5f31ac0f.png)

**Comment by wordmark** [comment]
Hi @handbye , thanks for reply. Are you able to see the following icon after opening a folder?
![untitled](https://user-images.githubusercontent.com/18313215/41084827-08072254-69ea-11e8-995c-a09c666de37f.png)

**Comment by handbye** [comment]
@wordmark  thanks for reply . I can see this icon.  One problem is that directories do not support multilevel display.  I want it to support directory structures in this form. it will be very good.
![360 16320216697183](https://user-images.githubusercontent.com/26617058/41169284-16d711c6-6b7b-11e8-9141-9b79eea593e9.png)

**Comment by wordmark** [comment]
Thanks @handbye . This feature is going to be added soon.

**Comment by handbye** [comment]
@wordmark  oh ,that will be great!  thanks
