### ISSUE TITLE
修改md文件,不能提交同样名称的文件.

### ISSUE THREAD

**Issue by hr1ycfl** [wordmark/wordmark#83]
当我提交过一篇文章之后,发现文章有问题.然后去修改,这个时候只能把原来的文件删除之后,才能提交.

希望可以增加 更新原来的文章的功能

**Comment by wordmark** [comment]
Original: hope to add a feature that allows users to update/edit instead of publishing a new post.

**Comment by wordmark** [comment]
Thanks. Will add that soon

**Comment by hr1ycfl** [comment]
我前几天刚买过 license ,等3.0正式版之后,还能继续使用吗?

**Comment by wordmark** [comment]
@hr1ycfl Yes.
