### ISSUE TITLE
为什么不能增加一个默认的文件夹呢?

### ISSUE THREAD

**Issue by hr1ycfl** [wordmark/wordmark#84]
每次打开都需要去点击一下 ,这很不合理.
希望增加默认文件夹,或者默认使用上次关闭的时候使用的文件夹
还有需要打开上次编辑的文件.

**Comment by hr1ycfl** [comment]
希望可以增加 默认就是编辑器页面,而不是需要去点新增文件才可以编辑,这是很不方便的.如果可以使编辑器页面增加一些默认的段落 之类的,那就更好了...

**Comment by wordmark** [comment]
Original question: request to add a default folder/file that the user does not have to do one more click.

@hr1ycfl Thanks for your suggestion. I am also thinking about it. For now if you open a folder, there is no way for you to open a different one unless you open a new window. But I will definitely come up with another method hopefully.

**Comment by hr1ycfl** [comment]
我认为可以参考一下 Visual Studio Code  的编辑。

**Comment by wordmark** [comment]
For now just added "Starred" and "Recent" for quick access (3.0.1-beta.9). You can also start to edit a new unsaved file upon opening a new window. Please let me know if you have better suggestions :)
