### ISSUE TITLE
Windows版上传图片至图床后无法正确得到链接地址

### ISSUE THREAD

**Issue by kekehurry** [wordmark/wordmark#86]

**Comment by wordmark** [comment]
Could you let me know which image service you are using?

**Comment by kekehurry** [comment]
Wordpress，mac版也存在这个问题，上传图片后链接显示![](object object)

**Comment by wordmark** [comment]
@kekehurry Thanks for confirming. I have reproduced it. Will fix.

**Comment by fuermosi777** [comment]
Should be fixed here https://github.com/wordmark/wordmark/releases/tag/v3.0.1-beta.8

**Comment by wordmark** [comment]
Should have been fixed in the[ latest release](https://github.com/wordmark/wordmark/releases/tag/v3.0.1-beta.8).
