### ISSUE TITLE
Preference tabs does not work

### ISSUE THREAD

**Issue by jenstornell** [wordmark/wordmark#88]
Clicking the tabs does not work. It also says "Preferences NULL".

Sometimes they work and sometimes not.

**Comment by wordmark** [comment]
Hi @jenstornell I am not sure what happened here. I wonder if you could send a screenshot of the preference window to hi@wordmarkapp.com so that I can take a deep look? Thanks!

**Comment by wordmark** [comment]
Should have fixed: https://github.com/wordmark/wordmark/releases/tag/v3.0.1-beta.15
Please let me know if it still happens. Thanks.
