### ISSUE TITLE
Publish 链接不上 GitHub Services  

### ISSUE THREAD

**Issue by hr1ycfl** [wordmark/wordmark#89]
![image](https://user-images.githubusercontent.com/22468684/45861907-d7a37c00-bda1-11e8-8e3a-6993a74d6197.png)

![image](https://user-images.githubusercontent.com/22468684/45861917-edb13c80-bda1-11e8-8b78-646aa995fb36.png)

一直在加载。。。

**Comment by wordmark** [comment]
Should have fixed https://github.com/wordmark/wordmark/releases/tag/v3.0.1-beta.15
Please let me know if it still happens. Thanks.
