### ISSUE TITLE
Small Bug: Preference Tab Extra Character

### ISSUE THREAD

**Issue by nukedart** [wordmark/wordmark#90]
**OS:** Windows 10
**WordMark** Version: 3.0.1-beta.16

Seems there is an extra character on the Preferences Tab. 

![snag_baf6cb](https://user-images.githubusercontent.com/7054271/46429728-327b9280-c715-11e8-84af-fda471fdfdef.png)

**Comment by wordmark** [comment]
Thanks for reporting this. Will fix.

**Comment by wordmark** [comment]
Fixed.
