### ISSUE TITLE
不可以直接复制粘贴图片自动上传的吗？

### ISSUE THREAD

**Issue by songborong** [wordmark/wordmark#91]
如题

**Comment by jaybenjaminlee** [comment]
我也想问，这个功能感觉是这个软件最好用的功能

**Comment by wordmark** [comment]
Thanks 😘, will add this.

**Comment by wordmark** [comment]
Feature added in [3.0.1-beta.18](https://github.com/wordmark/wordmark/releases/tag/v3.0.1-beta.18)
